// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The default team ID to use for resources that require a team ID or a team slug. Warning: Changing this value may not trigger recreation of resources.
func GetDefaultTeamId(ctx *pulumi.Context) string {
	return config.Get(ctx, "netlify:defaultTeamId")
}

// The default team slug to use for resources that require a team ID or a team slug. Warning: Changing this value may not trigger recreation of resources.
func GetDefaultTeamSlug(ctx *pulumi.Context) string {
	return config.Get(ctx, "netlify:defaultTeamSlug")
}

// Defaults to: https://api.netlify.com
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "netlify:endpoint")
}

// Read: https://docs.netlify.com/api/get-started/#authentication , will use the `NETLIFY_API_TOKEN` environment variable if not set.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "netlify:token")
}
