// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DeployKey struct {
	pulumi.CustomResourceState

	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	PublicKey   pulumi.StringOutput `pulumi:"publicKey"`
}

// NewDeployKey registers a new resource with the given unique name, arguments, and options.
func NewDeployKey(ctx *pulumi.Context,
	name string, args *DeployKeyArgs, opts ...pulumi.ResourceOption) (*DeployKey, error) {
	if args == nil {
		args = &DeployKeyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource DeployKey
	err = ctx.RegisterPackageResource("netlify:index/deployKey:DeployKey", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDeployKey gets an existing DeployKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDeployKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DeployKeyState, opts ...pulumi.ResourceOption) (*DeployKey, error) {
	var resource DeployKey
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/deployKey:DeployKey", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DeployKey resources.
type deployKeyState struct {
	LastUpdated *string `pulumi:"lastUpdated"`
	PublicKey   *string `pulumi:"publicKey"`
}

type DeployKeyState struct {
	LastUpdated pulumi.StringPtrInput
	PublicKey   pulumi.StringPtrInput
}

func (DeployKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*deployKeyState)(nil)).Elem()
}

type deployKeyArgs struct {
}

// The set of arguments for constructing a DeployKey resource.
type DeployKeyArgs struct {
}

func (DeployKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*deployKeyArgs)(nil)).Elem()
}

type DeployKeyInput interface {
	pulumi.Input

	ToDeployKeyOutput() DeployKeyOutput
	ToDeployKeyOutputWithContext(ctx context.Context) DeployKeyOutput
}

func (*DeployKey) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployKey)(nil)).Elem()
}

func (i *DeployKey) ToDeployKeyOutput() DeployKeyOutput {
	return i.ToDeployKeyOutputWithContext(context.Background())
}

func (i *DeployKey) ToDeployKeyOutputWithContext(ctx context.Context) DeployKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployKeyOutput)
}

type DeployKeyOutput struct{ *pulumi.OutputState }

func (DeployKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployKey)(nil)).Elem()
}

func (o DeployKeyOutput) ToDeployKeyOutput() DeployKeyOutput {
	return o
}

func (o DeployKeyOutput) ToDeployKeyOutputWithContext(ctx context.Context) DeployKeyOutput {
	return o
}

func (o DeployKeyOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o DeployKeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DeployKeyInput)(nil)).Elem(), &DeployKey{})
	pulumi.RegisterOutputType(DeployKeyOutput{})
}
