// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DnsRecord struct {
	pulumi.CustomResourceState

	Flag pulumi.Float64Output `pulumi:"flag"`
	// The hostname for the DNS record. For example, `www.example.com`.
	Hostname    pulumi.StringOutput  `pulumi:"hostname"`
	LastUpdated pulumi.StringOutput  `pulumi:"lastUpdated"`
	Priority    pulumi.Float64Output `pulumi:"priority"`
	Tag         pulumi.StringOutput  `pulumi:"tag"`
	Ttl         pulumi.Float64Output `pulumi:"ttl"`
	// One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
	Type   pulumi.StringOutput `pulumi:"type"`
	Value  pulumi.StringOutput `pulumi:"value"`
	ZoneId pulumi.StringOutput `pulumi:"zoneId"`
}

// NewDnsRecord registers a new resource with the given unique name, arguments, and options.
func NewDnsRecord(ctx *pulumi.Context,
	name string, args *DnsRecordArgs, opts ...pulumi.ResourceOption) (*DnsRecord, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Hostname == nil {
		return nil, errors.New("invalid value for required argument 'Hostname'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	if args.ZoneId == nil {
		return nil, errors.New("invalid value for required argument 'ZoneId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource DnsRecord
	err = ctx.RegisterPackageResource("netlify:index/dnsRecord:DnsRecord", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDnsRecord gets an existing DnsRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDnsRecord(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnsRecordState, opts ...pulumi.ResourceOption) (*DnsRecord, error) {
	var resource DnsRecord
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/dnsRecord:DnsRecord", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DnsRecord resources.
type dnsRecordState struct {
	Flag *float64 `pulumi:"flag"`
	// The hostname for the DNS record. For example, `www.example.com`.
	Hostname    *string  `pulumi:"hostname"`
	LastUpdated *string  `pulumi:"lastUpdated"`
	Priority    *float64 `pulumi:"priority"`
	Tag         *string  `pulumi:"tag"`
	Ttl         *float64 `pulumi:"ttl"`
	// One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
	Type   *string `pulumi:"type"`
	Value  *string `pulumi:"value"`
	ZoneId *string `pulumi:"zoneId"`
}

type DnsRecordState struct {
	Flag pulumi.Float64PtrInput
	// The hostname for the DNS record. For example, `www.example.com`.
	Hostname    pulumi.StringPtrInput
	LastUpdated pulumi.StringPtrInput
	Priority    pulumi.Float64PtrInput
	Tag         pulumi.StringPtrInput
	Ttl         pulumi.Float64PtrInput
	// One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
	Type   pulumi.StringPtrInput
	Value  pulumi.StringPtrInput
	ZoneId pulumi.StringPtrInput
}

func (DnsRecordState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsRecordState)(nil)).Elem()
}

type dnsRecordArgs struct {
	Flag *float64 `pulumi:"flag"`
	// The hostname for the DNS record. For example, `www.example.com`.
	Hostname string   `pulumi:"hostname"`
	Priority *float64 `pulumi:"priority"`
	Tag      *string  `pulumi:"tag"`
	Ttl      *float64 `pulumi:"ttl"`
	// One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
	Type   string `pulumi:"type"`
	Value  string `pulumi:"value"`
	ZoneId string `pulumi:"zoneId"`
}

// The set of arguments for constructing a DnsRecord resource.
type DnsRecordArgs struct {
	Flag pulumi.Float64PtrInput
	// The hostname for the DNS record. For example, `www.example.com`.
	Hostname pulumi.StringInput
	Priority pulumi.Float64PtrInput
	Tag      pulumi.StringPtrInput
	Ttl      pulumi.Float64PtrInput
	// One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
	Type   pulumi.StringInput
	Value  pulumi.StringInput
	ZoneId pulumi.StringInput
}

func (DnsRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsRecordArgs)(nil)).Elem()
}

type DnsRecordInput interface {
	pulumi.Input

	ToDnsRecordOutput() DnsRecordOutput
	ToDnsRecordOutputWithContext(ctx context.Context) DnsRecordOutput
}

func (*DnsRecord) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsRecord)(nil)).Elem()
}

func (i *DnsRecord) ToDnsRecordOutput() DnsRecordOutput {
	return i.ToDnsRecordOutputWithContext(context.Background())
}

func (i *DnsRecord) ToDnsRecordOutputWithContext(ctx context.Context) DnsRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsRecordOutput)
}

type DnsRecordOutput struct{ *pulumi.OutputState }

func (DnsRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsRecord)(nil)).Elem()
}

func (o DnsRecordOutput) ToDnsRecordOutput() DnsRecordOutput {
	return o
}

func (o DnsRecordOutput) ToDnsRecordOutputWithContext(ctx context.Context) DnsRecordOutput {
	return o
}

func (o DnsRecordOutput) Flag() pulumi.Float64Output {
	return o.ApplyT(func(v *DnsRecord) pulumi.Float64Output { return v.Flag }).(pulumi.Float64Output)
}

// The hostname for the DNS record. For example, `www.example.com`.
func (o DnsRecordOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

func (o DnsRecordOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o DnsRecordOutput) Priority() pulumi.Float64Output {
	return o.ApplyT(func(v *DnsRecord) pulumi.Float64Output { return v.Priority }).(pulumi.Float64Output)
}

func (o DnsRecordOutput) Tag() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Tag }).(pulumi.StringOutput)
}

func (o DnsRecordOutput) Ttl() pulumi.Float64Output {
	return o.ApplyT(func(v *DnsRecord) pulumi.Float64Output { return v.Ttl }).(pulumi.Float64Output)
}

// One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
func (o DnsRecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func (o DnsRecordOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

func (o DnsRecordOutput) ZoneId() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.ZoneId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnsRecordInput)(nil)).Elem(), &DnsRecord{})
	pulumi.RegisterOutputType(DnsRecordOutput{})
}
