// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DnsZone struct {
	pulumi.CustomResourceState

	DnsServers  pulumi.StringArrayOutput `pulumi:"dnsServers"`
	Domain      DnsZoneDomainOutput      `pulumi:"domain"`
	LastUpdated pulumi.StringOutput      `pulumi:"lastUpdated"`
	Name        pulumi.StringOutput      `pulumi:"name"`
	TeamId      pulumi.StringOutput      `pulumi:"teamId"`
	// Required if a default team was not configured in the provider configuration.
	TeamSlug pulumi.StringOutput `pulumi:"teamSlug"`
}

// NewDnsZone registers a new resource with the given unique name, arguments, and options.
func NewDnsZone(ctx *pulumi.Context,
	name string, args *DnsZoneArgs, opts ...pulumi.ResourceOption) (*DnsZone, error) {
	if args == nil {
		args = &DnsZoneArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource DnsZone
	err = ctx.RegisterPackageResource("netlify:index/dnsZone:DnsZone", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDnsZone gets an existing DnsZone resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDnsZone(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnsZoneState, opts ...pulumi.ResourceOption) (*DnsZone, error) {
	var resource DnsZone
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/dnsZone:DnsZone", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DnsZone resources.
type dnsZoneState struct {
	DnsServers  []string       `pulumi:"dnsServers"`
	Domain      *DnsZoneDomain `pulumi:"domain"`
	LastUpdated *string        `pulumi:"lastUpdated"`
	Name        *string        `pulumi:"name"`
	TeamId      *string        `pulumi:"teamId"`
	// Required if a default team was not configured in the provider configuration.
	TeamSlug *string `pulumi:"teamSlug"`
}

type DnsZoneState struct {
	DnsServers  pulumi.StringArrayInput
	Domain      DnsZoneDomainPtrInput
	LastUpdated pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	TeamId      pulumi.StringPtrInput
	// Required if a default team was not configured in the provider configuration.
	TeamSlug pulumi.StringPtrInput
}

func (DnsZoneState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsZoneState)(nil)).Elem()
}

type dnsZoneArgs struct {
	Name *string `pulumi:"name"`
	// Required if a default team was not configured in the provider configuration.
	TeamSlug *string `pulumi:"teamSlug"`
}

// The set of arguments for constructing a DnsZone resource.
type DnsZoneArgs struct {
	Name pulumi.StringPtrInput
	// Required if a default team was not configured in the provider configuration.
	TeamSlug pulumi.StringPtrInput
}

func (DnsZoneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsZoneArgs)(nil)).Elem()
}

type DnsZoneInput interface {
	pulumi.Input

	ToDnsZoneOutput() DnsZoneOutput
	ToDnsZoneOutputWithContext(ctx context.Context) DnsZoneOutput
}

func (*DnsZone) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsZone)(nil)).Elem()
}

func (i *DnsZone) ToDnsZoneOutput() DnsZoneOutput {
	return i.ToDnsZoneOutputWithContext(context.Background())
}

func (i *DnsZone) ToDnsZoneOutputWithContext(ctx context.Context) DnsZoneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsZoneOutput)
}

type DnsZoneOutput struct{ *pulumi.OutputState }

func (DnsZoneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsZone)(nil)).Elem()
}

func (o DnsZoneOutput) ToDnsZoneOutput() DnsZoneOutput {
	return o
}

func (o DnsZoneOutput) ToDnsZoneOutputWithContext(ctx context.Context) DnsZoneOutput {
	return o
}

func (o DnsZoneOutput) DnsServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DnsZone) pulumi.StringArrayOutput { return v.DnsServers }).(pulumi.StringArrayOutput)
}

func (o DnsZoneOutput) Domain() DnsZoneDomainOutput {
	return o.ApplyT(func(v *DnsZone) DnsZoneDomainOutput { return v.Domain }).(DnsZoneDomainOutput)
}

func (o DnsZoneOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsZone) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o DnsZoneOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsZone) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o DnsZoneOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsZone) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

// Required if a default team was not configured in the provider configuration.
func (o DnsZoneOutput) TeamSlug() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsZone) pulumi.StringOutput { return v.TeamSlug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnsZoneInput)(nil)).Elem(), &DnsZone{})
	pulumi.RegisterOutputType(DnsZoneOutput{})
}
