// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type EnvironmentVariable struct {
	pulumi.CustomResourceState

	Key         pulumi.StringOutput `pulumi:"key"`
	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	// One or more of builds, functions, runtime, and post-processing.
	//
	// Customizing scopes is not supported on free plans. However, free plan users managing a secret environment variable can and must explicitly set this to `["builds", "functions", "runtime"]`.
	Scopes       pulumi.StringArrayOutput                  `pulumi:"scopes"`
	SecretValues EnvironmentVariableSecretValueArrayOutput `pulumi:"secretValues"`
	SiteId       pulumi.StringPtrOutput                    `pulumi:"siteId"`
	// Required if a default team was not configured in the provider configuration.
	TeamId pulumi.StringOutput                 `pulumi:"teamId"`
	Values EnvironmentVariableValueArrayOutput `pulumi:"values"`
}

// NewEnvironmentVariable registers a new resource with the given unique name, arguments, and options.
func NewEnvironmentVariable(ctx *pulumi.Context,
	name string, args *EnvironmentVariableArgs, opts ...pulumi.ResourceOption) (*EnvironmentVariable, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource EnvironmentVariable
	err = ctx.RegisterPackageResource("netlify:index/environmentVariable:EnvironmentVariable", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironmentVariable gets an existing EnvironmentVariable resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironmentVariable(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnvironmentVariableState, opts ...pulumi.ResourceOption) (*EnvironmentVariable, error) {
	var resource EnvironmentVariable
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/environmentVariable:EnvironmentVariable", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EnvironmentVariable resources.
type environmentVariableState struct {
	Key         *string `pulumi:"key"`
	LastUpdated *string `pulumi:"lastUpdated"`
	// One or more of builds, functions, runtime, and post-processing.
	//
	// Customizing scopes is not supported on free plans. However, free plan users managing a secret environment variable can and must explicitly set this to `["builds", "functions", "runtime"]`.
	Scopes       []string                         `pulumi:"scopes"`
	SecretValues []EnvironmentVariableSecretValue `pulumi:"secretValues"`
	SiteId       *string                          `pulumi:"siteId"`
	// Required if a default team was not configured in the provider configuration.
	TeamId *string                    `pulumi:"teamId"`
	Values []EnvironmentVariableValue `pulumi:"values"`
}

type EnvironmentVariableState struct {
	Key         pulumi.StringPtrInput
	LastUpdated pulumi.StringPtrInput
	// One or more of builds, functions, runtime, and post-processing.
	//
	// Customizing scopes is not supported on free plans. However, free plan users managing a secret environment variable can and must explicitly set this to `["builds", "functions", "runtime"]`.
	Scopes       pulumi.StringArrayInput
	SecretValues EnvironmentVariableSecretValueArrayInput
	SiteId       pulumi.StringPtrInput
	// Required if a default team was not configured in the provider configuration.
	TeamId pulumi.StringPtrInput
	Values EnvironmentVariableValueArrayInput
}

func (EnvironmentVariableState) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentVariableState)(nil)).Elem()
}

type environmentVariableArgs struct {
	Key string `pulumi:"key"`
	// One or more of builds, functions, runtime, and post-processing.
	//
	// Customizing scopes is not supported on free plans. However, free plan users managing a secret environment variable can and must explicitly set this to `["builds", "functions", "runtime"]`.
	Scopes       []string                         `pulumi:"scopes"`
	SecretValues []EnvironmentVariableSecretValue `pulumi:"secretValues"`
	SiteId       *string                          `pulumi:"siteId"`
	// Required if a default team was not configured in the provider configuration.
	TeamId *string                    `pulumi:"teamId"`
	Values []EnvironmentVariableValue `pulumi:"values"`
}

// The set of arguments for constructing a EnvironmentVariable resource.
type EnvironmentVariableArgs struct {
	Key pulumi.StringInput
	// One or more of builds, functions, runtime, and post-processing.
	//
	// Customizing scopes is not supported on free plans. However, free plan users managing a secret environment variable can and must explicitly set this to `["builds", "functions", "runtime"]`.
	Scopes       pulumi.StringArrayInput
	SecretValues EnvironmentVariableSecretValueArrayInput
	SiteId       pulumi.StringPtrInput
	// Required if a default team was not configured in the provider configuration.
	TeamId pulumi.StringPtrInput
	Values EnvironmentVariableValueArrayInput
}

func (EnvironmentVariableArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentVariableArgs)(nil)).Elem()
}

type EnvironmentVariableInput interface {
	pulumi.Input

	ToEnvironmentVariableOutput() EnvironmentVariableOutput
	ToEnvironmentVariableOutputWithContext(ctx context.Context) EnvironmentVariableOutput
}

func (*EnvironmentVariable) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentVariable)(nil)).Elem()
}

func (i *EnvironmentVariable) ToEnvironmentVariableOutput() EnvironmentVariableOutput {
	return i.ToEnvironmentVariableOutputWithContext(context.Background())
}

func (i *EnvironmentVariable) ToEnvironmentVariableOutputWithContext(ctx context.Context) EnvironmentVariableOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentVariableOutput)
}

type EnvironmentVariableOutput struct{ *pulumi.OutputState }

func (EnvironmentVariableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentVariable)(nil)).Elem()
}

func (o EnvironmentVariableOutput) ToEnvironmentVariableOutput() EnvironmentVariableOutput {
	return o
}

func (o EnvironmentVariableOutput) ToEnvironmentVariableOutputWithContext(ctx context.Context) EnvironmentVariableOutput {
	return o
}

func (o EnvironmentVariableOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentVariable) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

func (o EnvironmentVariableOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentVariable) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// One or more of builds, functions, runtime, and post-processing.
//
// Customizing scopes is not supported on free plans. However, free plan users managing a secret environment variable can and must explicitly set this to `["builds", "functions", "runtime"]`.
func (o EnvironmentVariableOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *EnvironmentVariable) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

func (o EnvironmentVariableOutput) SecretValues() EnvironmentVariableSecretValueArrayOutput {
	return o.ApplyT(func(v *EnvironmentVariable) EnvironmentVariableSecretValueArrayOutput { return v.SecretValues }).(EnvironmentVariableSecretValueArrayOutput)
}

func (o EnvironmentVariableOutput) SiteId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EnvironmentVariable) pulumi.StringPtrOutput { return v.SiteId }).(pulumi.StringPtrOutput)
}

// Required if a default team was not configured in the provider configuration.
func (o EnvironmentVariableOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentVariable) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

func (o EnvironmentVariableOutput) Values() EnvironmentVariableValueArrayOutput {
	return o.ApplyT(func(v *EnvironmentVariable) EnvironmentVariableValueArrayOutput { return v.Values }).(EnvironmentVariableValueArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentVariableInput)(nil)).Elem(), &EnvironmentVariable{})
	pulumi.RegisterOutputType(EnvironmentVariableOutput{})
}
