// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDnsZone(ctx *pulumi.Context, args *LookupDnsZoneArgs, opts ...pulumi.InvokeOption) (*LookupDnsZoneResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupDnsZoneResult
	err = ctx.InvokePackage("netlify:index/getDnsZone:getDnsZone", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDnsZone.
type LookupDnsZoneArgs struct {
	Id   *string `pulumi:"id"`
	Name *string `pulumi:"name"`
}

// A collection of values returned by getDnsZone.
type LookupDnsZoneResult struct {
	DnsServers []string           `pulumi:"dnsServers"`
	Domain     GetDnsZoneDomain   `pulumi:"domain"`
	Id         string             `pulumi:"id"`
	Name       string             `pulumi:"name"`
	Records    []GetDnsZoneRecord `pulumi:"records"`
	TeamId     string             `pulumi:"teamId"`
	TeamSlug   string             `pulumi:"teamSlug"`
}

func LookupDnsZoneOutput(ctx *pulumi.Context, args LookupDnsZoneOutputArgs, opts ...pulumi.InvokeOption) LookupDnsZoneResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupDnsZoneResultOutput, error) {
			args := v.(LookupDnsZoneArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupDnsZoneResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("netlify:index/getDnsZone:getDnsZone", args, LookupDnsZoneResultOutput{}, options).(LookupDnsZoneResultOutput), nil
		}).(LookupDnsZoneResultOutput)
}

// A collection of arguments for invoking getDnsZone.
type LookupDnsZoneOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupDnsZoneOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDnsZoneArgs)(nil)).Elem()
}

// A collection of values returned by getDnsZone.
type LookupDnsZoneResultOutput struct{ *pulumi.OutputState }

func (LookupDnsZoneResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDnsZoneResult)(nil)).Elem()
}

func (o LookupDnsZoneResultOutput) ToLookupDnsZoneResultOutput() LookupDnsZoneResultOutput {
	return o
}

func (o LookupDnsZoneResultOutput) ToLookupDnsZoneResultOutputWithContext(ctx context.Context) LookupDnsZoneResultOutput {
	return o
}

func (o LookupDnsZoneResultOutput) DnsServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) []string { return v.DnsServers }).(pulumi.StringArrayOutput)
}

func (o LookupDnsZoneResultOutput) Domain() GetDnsZoneDomainOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) GetDnsZoneDomain { return v.Domain }).(GetDnsZoneDomainOutput)
}

func (o LookupDnsZoneResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDnsZoneResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDnsZoneResultOutput) Records() GetDnsZoneRecordArrayOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) []GetDnsZoneRecord { return v.Records }).(GetDnsZoneRecordArrayOutput)
}

func (o LookupDnsZoneResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) string { return v.TeamId }).(pulumi.StringOutput)
}

func (o LookupDnsZoneResultOutput) TeamSlug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDnsZoneResult) string { return v.TeamSlug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDnsZoneResultOutput{})
}
