// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetManagedWafRules(ctx *pulumi.Context, args *GetManagedWafRulesArgs, opts ...pulumi.InvokeOption) (*GetManagedWafRulesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetManagedWafRulesResult
	err = ctx.InvokePackage("netlify:index/getManagedWafRules:getManagedWafRules", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getManagedWafRules.
type GetManagedWafRulesArgs struct {
	TeamId string `pulumi:"teamId"`
}

// A collection of values returned by getManagedWafRules.
type GetManagedWafRulesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id       string                                `pulumi:"id"`
	RuleSets map[string]GetManagedWafRulesRuleSets `pulumi:"ruleSets"`
	TeamId   string                                `pulumi:"teamId"`
}

func GetManagedWafRulesOutput(ctx *pulumi.Context, args GetManagedWafRulesOutputArgs, opts ...pulumi.InvokeOption) GetManagedWafRulesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetManagedWafRulesResultOutput, error) {
			args := v.(GetManagedWafRulesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetManagedWafRulesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("netlify:index/getManagedWafRules:getManagedWafRules", args, GetManagedWafRulesResultOutput{}, options).(GetManagedWafRulesResultOutput), nil
		}).(GetManagedWafRulesResultOutput)
}

// A collection of arguments for invoking getManagedWafRules.
type GetManagedWafRulesOutputArgs struct {
	TeamId pulumi.StringInput `pulumi:"teamId"`
}

func (GetManagedWafRulesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetManagedWafRulesArgs)(nil)).Elem()
}

// A collection of values returned by getManagedWafRules.
type GetManagedWafRulesResultOutput struct{ *pulumi.OutputState }

func (GetManagedWafRulesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetManagedWafRulesResult)(nil)).Elem()
}

func (o GetManagedWafRulesResultOutput) ToGetManagedWafRulesResultOutput() GetManagedWafRulesResultOutput {
	return o
}

func (o GetManagedWafRulesResultOutput) ToGetManagedWafRulesResultOutputWithContext(ctx context.Context) GetManagedWafRulesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetManagedWafRulesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagedWafRulesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetManagedWafRulesResultOutput) RuleSets() GetManagedWafRulesRuleSetsMapOutput {
	return o.ApplyT(func(v GetManagedWafRulesResult) map[string]GetManagedWafRulesRuleSets { return v.RuleSets }).(GetManagedWafRulesRuleSetsMapOutput)
}

func (o GetManagedWafRulesResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v GetManagedWafRulesResult) string { return v.TeamId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetManagedWafRulesResultOutput{})
}
