// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSites(ctx *pulumi.Context, args *GetSitesArgs, opts ...pulumi.InvokeOption) (*GetSitesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetSitesResult
	err = ctx.InvokePackage("netlify:index/getSites:getSites", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSites.
type GetSitesArgs struct {
	TeamSlug *string `pulumi:"teamSlug"`
}

// A collection of values returned by getSites.
type GetSitesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id       string         `pulumi:"id"`
	Sites    []GetSitesSite `pulumi:"sites"`
	TeamSlug string         `pulumi:"teamSlug"`
}

func GetSitesOutput(ctx *pulumi.Context, args GetSitesOutputArgs, opts ...pulumi.InvokeOption) GetSitesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSitesResultOutput, error) {
			args := v.(GetSitesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetSitesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("netlify:index/getSites:getSites", args, GetSitesResultOutput{}, options).(GetSitesResultOutput), nil
		}).(GetSitesResultOutput)
}

// A collection of arguments for invoking getSites.
type GetSitesOutputArgs struct {
	TeamSlug pulumi.StringPtrInput `pulumi:"teamSlug"`
}

func (GetSitesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSitesArgs)(nil)).Elem()
}

// A collection of values returned by getSites.
type GetSitesResultOutput struct{ *pulumi.OutputState }

func (GetSitesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSitesResult)(nil)).Elem()
}

func (o GetSitesResultOutput) ToGetSitesResultOutput() GetSitesResultOutput {
	return o
}

func (o GetSitesResultOutput) ToGetSitesResultOutputWithContext(ctx context.Context) GetSitesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetSitesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSitesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSitesResultOutput) Sites() GetSitesSiteArrayOutput {
	return o.ApplyT(func(v GetSitesResult) []GetSitesSite { return v.Sites }).(GetSitesSiteArrayOutput)
}

func (o GetSitesResultOutput) TeamSlug() pulumi.StringOutput {
	return o.ApplyT(func(v GetSitesResult) string { return v.TeamSlug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSitesResultOutput{})
}
