// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSite(ctx *pulumi.Context, args *GetSiteArgs, opts ...pulumi.InvokeOption) (*GetSiteResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetSiteResult
	err = ctx.InvokePackage("netlify:index/getSite:getSite", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSite.
type GetSiteArgs struct {
	Id       *string `pulumi:"id"`
	Name     *string `pulumi:"name"`
	TeamSlug *string `pulumi:"teamSlug"`
}

// A collection of values returned by getSite.
type GetSiteResult struct {
	CustomDomain  string   `pulumi:"customDomain"`
	DomainAliases []string `pulumi:"domainAliases"`
	GitDeployKey  string   `pulumi:"gitDeployKey"`
	Id            string   `pulumi:"id"`
	Name          string   `pulumi:"name"`
	TeamSlug      string   `pulumi:"teamSlug"`
}

func GetSiteOutput(ctx *pulumi.Context, args GetSiteOutputArgs, opts ...pulumi.InvokeOption) GetSiteResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSiteResultOutput, error) {
			args := v.(GetSiteArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetSiteResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("netlify:index/getSite:getSite", args, GetSiteResultOutput{}, options).(GetSiteResultOutput), nil
		}).(GetSiteResultOutput)
}

// A collection of arguments for invoking getSite.
type GetSiteOutputArgs struct {
	Id       pulumi.StringPtrInput `pulumi:"id"`
	Name     pulumi.StringPtrInput `pulumi:"name"`
	TeamSlug pulumi.StringPtrInput `pulumi:"teamSlug"`
}

func (GetSiteOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSiteArgs)(nil)).Elem()
}

// A collection of values returned by getSite.
type GetSiteResultOutput struct{ *pulumi.OutputState }

func (GetSiteResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSiteResult)(nil)).Elem()
}

func (o GetSiteResultOutput) ToGetSiteResultOutput() GetSiteResultOutput {
	return o
}

func (o GetSiteResultOutput) ToGetSiteResultOutputWithContext(ctx context.Context) GetSiteResultOutput {
	return o
}

func (o GetSiteResultOutput) CustomDomain() pulumi.StringOutput {
	return o.ApplyT(func(v GetSiteResult) string { return v.CustomDomain }).(pulumi.StringOutput)
}

func (o GetSiteResultOutput) DomainAliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSiteResult) []string { return v.DomainAliases }).(pulumi.StringArrayOutput)
}

func (o GetSiteResultOutput) GitDeployKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetSiteResult) string { return v.GitDeployKey }).(pulumi.StringOutput)
}

func (o GetSiteResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSiteResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSiteResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetSiteResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetSiteResultOutput) TeamSlug() pulumi.StringOutput {
	return o.ApplyT(func(v GetSiteResult) string { return v.TeamSlug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSiteResultOutput{})
}
