// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTeam(ctx *pulumi.Context, args *GetTeamArgs, opts ...pulumi.InvokeOption) (*GetTeamResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetTeamResult
	err = ctx.InvokePackage("netlify:index/getTeam:getTeam", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTeam.
type GetTeamArgs struct {
	Id   *string `pulumi:"id"`
	Slug *string `pulumi:"slug"`
}

// A collection of values returned by getTeam.
type GetTeamResult struct {
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func GetTeamOutput(ctx *pulumi.Context, args GetTeamOutputArgs, opts ...pulumi.InvokeOption) GetTeamResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetTeamResultOutput, error) {
			args := v.(GetTeamArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetTeamResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("netlify:index/getTeam:getTeam", args, GetTeamResultOutput{}, options).(GetTeamResultOutput), nil
		}).(GetTeamResultOutput)
}

// A collection of arguments for invoking getTeam.
type GetTeamOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Slug pulumi.StringPtrInput `pulumi:"slug"`
}

func (GetTeamOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTeamArgs)(nil)).Elem()
}

// A collection of values returned by getTeam.
type GetTeamResultOutput struct{ *pulumi.OutputState }

func (GetTeamResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTeamResult)(nil)).Elem()
}

func (o GetTeamResultOutput) ToGetTeamResultOutput() GetTeamResultOutput {
	return o
}

func (o GetTeamResultOutput) ToGetTeamResultOutputWithContext(ctx context.Context) GetTeamResultOutput {
	return o
}

func (o GetTeamResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTeamResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTeamResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTeamResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetTeamResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v GetTeamResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTeamResultOutput{})
}
