// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "netlify:index/deployKey:DeployKey":
		r = &DeployKey{}
	case "netlify:index/dnsRecord:DnsRecord":
		r = &DnsRecord{}
	case "netlify:index/dnsZone:DnsZone":
		r = &DnsZone{}
	case "netlify:index/environmentVariable:EnvironmentVariable":
		r = &EnvironmentVariable{}
	case "netlify:index/logDrain:LogDrain":
		r = &LogDrain{}
	case "netlify:index/siteBuildSettings:SiteBuildSettings":
		r = &SiteBuildSettings{}
	case "netlify:index/siteCollaborationSettings:SiteCollaborationSettings":
		r = &SiteCollaborationSettings{}
	case "netlify:index/siteDomainSettings:SiteDomainSettings":
		r = &SiteDomainSettings{}
	case "netlify:index/siteFirewallTrafficRules:SiteFirewallTrafficRules":
		r = &SiteFirewallTrafficRules{}
	case "netlify:index/siteMetricsSettings:SiteMetricsSettings":
		r = &SiteMetricsSettings{}
	case "netlify:index/teamFirewallTrafficRules:TeamFirewallTrafficRules":
		r = &TeamFirewallTrafficRules{}
	case "netlify:index/wafPolicy:WafPolicy":
		r = &WafPolicy{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:netlify" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"netlify",
		"index/deployKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/dnsRecord",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/dnsZone",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/environmentVariable",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/logDrain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/siteBuildSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/siteCollaborationSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/siteDomainSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/siteFirewallTrafficRules",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/siteMetricsSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/teamFirewallTrafficRules",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netlify",
		"index/wafPolicy",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"netlify",
		&pkg{version},
	)
}
