// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LogDrain struct {
	pulumi.CustomResourceState

	// One of datadog, newrelic, logflare, s3, splunkcloud, http, axiom, or azure
	Destination pulumi.StringOutput `pulumi:"destination"`
	ExcludePii  pulumi.BoolOutput   `pulumi:"excludePii"`
	// json or ndjson
	Format      pulumi.StringOutput `pulumi:"format"`
	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	// One or more of user_traffic, functions, edge_functions, waf_logs, and deploys
	LogTypes      pulumi.StringArrayOutput    `pulumi:"logTypes"`
	ServiceConfig LogDrainServiceConfigOutput `pulumi:"serviceConfig"`
	SiteId        pulumi.StringOutput         `pulumi:"siteId"`
}

// NewLogDrain registers a new resource with the given unique name, arguments, and options.
func NewLogDrain(ctx *pulumi.Context,
	name string, args *LogDrainArgs, opts ...pulumi.ResourceOption) (*LogDrain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Destination == nil {
		return nil, errors.New("invalid value for required argument 'Destination'")
	}
	if args.ExcludePii == nil {
		return nil, errors.New("invalid value for required argument 'ExcludePii'")
	}
	if args.LogTypes == nil {
		return nil, errors.New("invalid value for required argument 'LogTypes'")
	}
	if args.ServiceConfig == nil {
		return nil, errors.New("invalid value for required argument 'ServiceConfig'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource LogDrain
	err = ctx.RegisterPackageResource("netlify:index/logDrain:LogDrain", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogDrain gets an existing LogDrain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogDrain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogDrainState, opts ...pulumi.ResourceOption) (*LogDrain, error) {
	var resource LogDrain
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/logDrain:LogDrain", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogDrain resources.
type logDrainState struct {
	// One of datadog, newrelic, logflare, s3, splunkcloud, http, axiom, or azure
	Destination *string `pulumi:"destination"`
	ExcludePii  *bool   `pulumi:"excludePii"`
	// json or ndjson
	Format      *string `pulumi:"format"`
	LastUpdated *string `pulumi:"lastUpdated"`
	// One or more of user_traffic, functions, edge_functions, waf_logs, and deploys
	LogTypes      []string               `pulumi:"logTypes"`
	ServiceConfig *LogDrainServiceConfig `pulumi:"serviceConfig"`
	SiteId        *string                `pulumi:"siteId"`
}

type LogDrainState struct {
	// One of datadog, newrelic, logflare, s3, splunkcloud, http, axiom, or azure
	Destination pulumi.StringPtrInput
	ExcludePii  pulumi.BoolPtrInput
	// json or ndjson
	Format      pulumi.StringPtrInput
	LastUpdated pulumi.StringPtrInput
	// One or more of user_traffic, functions, edge_functions, waf_logs, and deploys
	LogTypes      pulumi.StringArrayInput
	ServiceConfig LogDrainServiceConfigPtrInput
	SiteId        pulumi.StringPtrInput
}

func (LogDrainState) ElementType() reflect.Type {
	return reflect.TypeOf((*logDrainState)(nil)).Elem()
}

type logDrainArgs struct {
	// One of datadog, newrelic, logflare, s3, splunkcloud, http, axiom, or azure
	Destination string `pulumi:"destination"`
	ExcludePii  bool   `pulumi:"excludePii"`
	// json or ndjson
	Format *string `pulumi:"format"`
	// One or more of user_traffic, functions, edge_functions, waf_logs, and deploys
	LogTypes      []string              `pulumi:"logTypes"`
	ServiceConfig LogDrainServiceConfig `pulumi:"serviceConfig"`
	SiteId        string                `pulumi:"siteId"`
}

// The set of arguments for constructing a LogDrain resource.
type LogDrainArgs struct {
	// One of datadog, newrelic, logflare, s3, splunkcloud, http, axiom, or azure
	Destination pulumi.StringInput
	ExcludePii  pulumi.BoolInput
	// json or ndjson
	Format pulumi.StringPtrInput
	// One or more of user_traffic, functions, edge_functions, waf_logs, and deploys
	LogTypes      pulumi.StringArrayInput
	ServiceConfig LogDrainServiceConfigInput
	SiteId        pulumi.StringInput
}

func (LogDrainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*logDrainArgs)(nil)).Elem()
}

type LogDrainInput interface {
	pulumi.Input

	ToLogDrainOutput() LogDrainOutput
	ToLogDrainOutputWithContext(ctx context.Context) LogDrainOutput
}

func (*LogDrain) ElementType() reflect.Type {
	return reflect.TypeOf((**LogDrain)(nil)).Elem()
}

func (i *LogDrain) ToLogDrainOutput() LogDrainOutput {
	return i.ToLogDrainOutputWithContext(context.Background())
}

func (i *LogDrain) ToLogDrainOutputWithContext(ctx context.Context) LogDrainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogDrainOutput)
}

type LogDrainOutput struct{ *pulumi.OutputState }

func (LogDrainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LogDrain)(nil)).Elem()
}

func (o LogDrainOutput) ToLogDrainOutput() LogDrainOutput {
	return o
}

func (o LogDrainOutput) ToLogDrainOutputWithContext(ctx context.Context) LogDrainOutput {
	return o
}

// One of datadog, newrelic, logflare, s3, splunkcloud, http, axiom, or azure
func (o LogDrainOutput) Destination() pulumi.StringOutput {
	return o.ApplyT(func(v *LogDrain) pulumi.StringOutput { return v.Destination }).(pulumi.StringOutput)
}

func (o LogDrainOutput) ExcludePii() pulumi.BoolOutput {
	return o.ApplyT(func(v *LogDrain) pulumi.BoolOutput { return v.ExcludePii }).(pulumi.BoolOutput)
}

// json or ndjson
func (o LogDrainOutput) Format() pulumi.StringOutput {
	return o.ApplyT(func(v *LogDrain) pulumi.StringOutput { return v.Format }).(pulumi.StringOutput)
}

func (o LogDrainOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *LogDrain) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// One or more of user_traffic, functions, edge_functions, waf_logs, and deploys
func (o LogDrainOutput) LogTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LogDrain) pulumi.StringArrayOutput { return v.LogTypes }).(pulumi.StringArrayOutput)
}

func (o LogDrainOutput) ServiceConfig() LogDrainServiceConfigOutput {
	return o.ApplyT(func(v *LogDrain) LogDrainServiceConfigOutput { return v.ServiceConfig }).(LogDrainServiceConfigOutput)
}

func (o LogDrainOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *LogDrain) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LogDrainInput)(nil)).Elem(), &LogDrain{})
	pulumi.RegisterOutputType(LogDrainOutput{})
}
