// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SiteFirewallTrafficRules struct {
	pulumi.CustomResourceState

	LastUpdated pulumi.StringOutput                       `pulumi:"lastUpdated"`
	Published   SiteFirewallTrafficRulesPublishedOutput   `pulumi:"published"`
	SiteId      pulumi.StringOutput                       `pulumi:"siteId"`
	TeamId      pulumi.StringOutput                       `pulumi:"teamId"`
	Unpublished SiteFirewallTrafficRulesUnpublishedOutput `pulumi:"unpublished"`
}

// NewSiteFirewallTrafficRules registers a new resource with the given unique name, arguments, and options.
func NewSiteFirewallTrafficRules(ctx *pulumi.Context,
	name string, args *SiteFirewallTrafficRulesArgs, opts ...pulumi.ResourceOption) (*SiteFirewallTrafficRules, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Published == nil {
		return nil, errors.New("invalid value for required argument 'Published'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	if args.Unpublished == nil {
		return nil, errors.New("invalid value for required argument 'Unpublished'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SiteFirewallTrafficRules
	err = ctx.RegisterPackageResource("netlify:index/siteFirewallTrafficRules:SiteFirewallTrafficRules", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSiteFirewallTrafficRules gets an existing SiteFirewallTrafficRules resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSiteFirewallTrafficRules(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SiteFirewallTrafficRulesState, opts ...pulumi.ResourceOption) (*SiteFirewallTrafficRules, error) {
	var resource SiteFirewallTrafficRules
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/siteFirewallTrafficRules:SiteFirewallTrafficRules", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SiteFirewallTrafficRules resources.
type siteFirewallTrafficRulesState struct {
	LastUpdated *string                              `pulumi:"lastUpdated"`
	Published   *SiteFirewallTrafficRulesPublished   `pulumi:"published"`
	SiteId      *string                              `pulumi:"siteId"`
	TeamId      *string                              `pulumi:"teamId"`
	Unpublished *SiteFirewallTrafficRulesUnpublished `pulumi:"unpublished"`
}

type SiteFirewallTrafficRulesState struct {
	LastUpdated pulumi.StringPtrInput
	Published   SiteFirewallTrafficRulesPublishedPtrInput
	SiteId      pulumi.StringPtrInput
	TeamId      pulumi.StringPtrInput
	Unpublished SiteFirewallTrafficRulesUnpublishedPtrInput
}

func (SiteFirewallTrafficRulesState) ElementType() reflect.Type {
	return reflect.TypeOf((*siteFirewallTrafficRulesState)(nil)).Elem()
}

type siteFirewallTrafficRulesArgs struct {
	Published   SiteFirewallTrafficRulesPublished   `pulumi:"published"`
	SiteId      string                              `pulumi:"siteId"`
	Unpublished SiteFirewallTrafficRulesUnpublished `pulumi:"unpublished"`
}

// The set of arguments for constructing a SiteFirewallTrafficRules resource.
type SiteFirewallTrafficRulesArgs struct {
	Published   SiteFirewallTrafficRulesPublishedInput
	SiteId      pulumi.StringInput
	Unpublished SiteFirewallTrafficRulesUnpublishedInput
}

func (SiteFirewallTrafficRulesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*siteFirewallTrafficRulesArgs)(nil)).Elem()
}

type SiteFirewallTrafficRulesInput interface {
	pulumi.Input

	ToSiteFirewallTrafficRulesOutput() SiteFirewallTrafficRulesOutput
	ToSiteFirewallTrafficRulesOutputWithContext(ctx context.Context) SiteFirewallTrafficRulesOutput
}

func (*SiteFirewallTrafficRules) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteFirewallTrafficRules)(nil)).Elem()
}

func (i *SiteFirewallTrafficRules) ToSiteFirewallTrafficRulesOutput() SiteFirewallTrafficRulesOutput {
	return i.ToSiteFirewallTrafficRulesOutputWithContext(context.Background())
}

func (i *SiteFirewallTrafficRules) ToSiteFirewallTrafficRulesOutputWithContext(ctx context.Context) SiteFirewallTrafficRulesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SiteFirewallTrafficRulesOutput)
}

type SiteFirewallTrafficRulesOutput struct{ *pulumi.OutputState }

func (SiteFirewallTrafficRulesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteFirewallTrafficRules)(nil)).Elem()
}

func (o SiteFirewallTrafficRulesOutput) ToSiteFirewallTrafficRulesOutput() SiteFirewallTrafficRulesOutput {
	return o
}

func (o SiteFirewallTrafficRulesOutput) ToSiteFirewallTrafficRulesOutputWithContext(ctx context.Context) SiteFirewallTrafficRulesOutput {
	return o
}

func (o SiteFirewallTrafficRulesOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteFirewallTrafficRules) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o SiteFirewallTrafficRulesOutput) Published() SiteFirewallTrafficRulesPublishedOutput {
	return o.ApplyT(func(v *SiteFirewallTrafficRules) SiteFirewallTrafficRulesPublishedOutput { return v.Published }).(SiteFirewallTrafficRulesPublishedOutput)
}

func (o SiteFirewallTrafficRulesOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteFirewallTrafficRules) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func (o SiteFirewallTrafficRulesOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteFirewallTrafficRules) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

func (o SiteFirewallTrafficRulesOutput) Unpublished() SiteFirewallTrafficRulesUnpublishedOutput {
	return o.ApplyT(func(v *SiteFirewallTrafficRules) SiteFirewallTrafficRulesUnpublishedOutput { return v.Unpublished }).(SiteFirewallTrafficRulesUnpublishedOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SiteFirewallTrafficRulesInput)(nil)).Elem(), &SiteFirewallTrafficRules{})
	pulumi.RegisterOutputType(SiteFirewallTrafficRulesOutput{})
}
