// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SiteBuildSettings struct {
	pulumi.CustomResourceState

	BaseDirectory           pulumi.StringOutput      `pulumi:"baseDirectory"`
	BranchDeployAllBranches pulumi.BoolOutput        `pulumi:"branchDeployAllBranches"`
	BranchDeployBranches    pulumi.StringArrayOutput `pulumi:"branchDeployBranches"`
	BuildCommand            pulumi.StringOutput      `pulumi:"buildCommand"`
	BuildImage              pulumi.StringOutput      `pulumi:"buildImage"`
	DeployPreviews          pulumi.BoolOutput        `pulumi:"deployPreviews"`
	FunctionsDirectory      pulumi.StringOutput      `pulumi:"functionsDirectory"`
	FunctionsRegion         pulumi.StringOutput      `pulumi:"functionsRegion"`
	LastUpdated             pulumi.StringOutput      `pulumi:"lastUpdated"`
	PackageDirectory        pulumi.StringOutput      `pulumi:"packageDirectory"`
	PrettyUrls              pulumi.BoolOutput        `pulumi:"prettyUrls"`
	// When enabled, prevents production deploys from sources other than the linked git repository.
	PreventNonGitProdDeploys pulumi.BoolOutput   `pulumi:"preventNonGitProdDeploys"`
	ProductionBranch         pulumi.StringOutput `pulumi:"productionBranch"`
	PublishDirectory         pulumi.StringOutput `pulumi:"publishDirectory"`
	SiteId                   pulumi.StringOutput `pulumi:"siteId"`
	StopBuilds               pulumi.BoolOutput   `pulumi:"stopBuilds"`
	// See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy " pulumi-lang-hcl=" netlify_waf_policy "> netlify.WafPolicy </span>resource.
	WafPolicyId pulumi.StringPtrOutput `pulumi:"wafPolicyId"`
}

// NewSiteBuildSettings registers a new resource with the given unique name, arguments, and options.
func NewSiteBuildSettings(ctx *pulumi.Context,
	name string, args *SiteBuildSettingsArgs, opts ...pulumi.ResourceOption) (*SiteBuildSettings, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BuildCommand == nil {
		return nil, errors.New("invalid value for required argument 'BuildCommand'")
	}
	if args.ProductionBranch == nil {
		return nil, errors.New("invalid value for required argument 'ProductionBranch'")
	}
	if args.PublishDirectory == nil {
		return nil, errors.New("invalid value for required argument 'PublishDirectory'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SiteBuildSettings
	err = ctx.RegisterPackageResource("netlify:index/siteBuildSettings:SiteBuildSettings", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSiteBuildSettings gets an existing SiteBuildSettings resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSiteBuildSettings(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SiteBuildSettingsState, opts ...pulumi.ResourceOption) (*SiteBuildSettings, error) {
	var resource SiteBuildSettings
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/siteBuildSettings:SiteBuildSettings", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SiteBuildSettings resources.
type siteBuildSettingsState struct {
	BaseDirectory           *string  `pulumi:"baseDirectory"`
	BranchDeployAllBranches *bool    `pulumi:"branchDeployAllBranches"`
	BranchDeployBranches    []string `pulumi:"branchDeployBranches"`
	BuildCommand            *string  `pulumi:"buildCommand"`
	BuildImage              *string  `pulumi:"buildImage"`
	DeployPreviews          *bool    `pulumi:"deployPreviews"`
	FunctionsDirectory      *string  `pulumi:"functionsDirectory"`
	FunctionsRegion         *string  `pulumi:"functionsRegion"`
	LastUpdated             *string  `pulumi:"lastUpdated"`
	PackageDirectory        *string  `pulumi:"packageDirectory"`
	PrettyUrls              *bool    `pulumi:"prettyUrls"`
	// When enabled, prevents production deploys from sources other than the linked git repository.
	PreventNonGitProdDeploys *bool   `pulumi:"preventNonGitProdDeploys"`
	ProductionBranch         *string `pulumi:"productionBranch"`
	PublishDirectory         *string `pulumi:"publishDirectory"`
	SiteId                   *string `pulumi:"siteId"`
	StopBuilds               *bool   `pulumi:"stopBuilds"`
	// See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy " pulumi-lang-hcl=" netlify_waf_policy "> netlify.WafPolicy </span>resource.
	WafPolicyId *string `pulumi:"wafPolicyId"`
}

type SiteBuildSettingsState struct {
	BaseDirectory           pulumi.StringPtrInput
	BranchDeployAllBranches pulumi.BoolPtrInput
	BranchDeployBranches    pulumi.StringArrayInput
	BuildCommand            pulumi.StringPtrInput
	BuildImage              pulumi.StringPtrInput
	DeployPreviews          pulumi.BoolPtrInput
	FunctionsDirectory      pulumi.StringPtrInput
	FunctionsRegion         pulumi.StringPtrInput
	LastUpdated             pulumi.StringPtrInput
	PackageDirectory        pulumi.StringPtrInput
	PrettyUrls              pulumi.BoolPtrInput
	// When enabled, prevents production deploys from sources other than the linked git repository.
	PreventNonGitProdDeploys pulumi.BoolPtrInput
	ProductionBranch         pulumi.StringPtrInput
	PublishDirectory         pulumi.StringPtrInput
	SiteId                   pulumi.StringPtrInput
	StopBuilds               pulumi.BoolPtrInput
	// See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy " pulumi-lang-hcl=" netlify_waf_policy "> netlify.WafPolicy </span>resource.
	WafPolicyId pulumi.StringPtrInput
}

func (SiteBuildSettingsState) ElementType() reflect.Type {
	return reflect.TypeOf((*siteBuildSettingsState)(nil)).Elem()
}

type siteBuildSettingsArgs struct {
	BaseDirectory           *string  `pulumi:"baseDirectory"`
	BranchDeployAllBranches *bool    `pulumi:"branchDeployAllBranches"`
	BranchDeployBranches    []string `pulumi:"branchDeployBranches"`
	BuildCommand            string   `pulumi:"buildCommand"`
	BuildImage              *string  `pulumi:"buildImage"`
	DeployPreviews          *bool    `pulumi:"deployPreviews"`
	FunctionsDirectory      *string  `pulumi:"functionsDirectory"`
	FunctionsRegion         *string  `pulumi:"functionsRegion"`
	PackageDirectory        *string  `pulumi:"packageDirectory"`
	PrettyUrls              *bool    `pulumi:"prettyUrls"`
	// When enabled, prevents production deploys from sources other than the linked git repository.
	PreventNonGitProdDeploys *bool  `pulumi:"preventNonGitProdDeploys"`
	ProductionBranch         string `pulumi:"productionBranch"`
	PublishDirectory         string `pulumi:"publishDirectory"`
	SiteId                   string `pulumi:"siteId"`
	StopBuilds               *bool  `pulumi:"stopBuilds"`
	// See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy " pulumi-lang-hcl=" netlify_waf_policy "> netlify.WafPolicy </span>resource.
	WafPolicyId *string `pulumi:"wafPolicyId"`
}

// The set of arguments for constructing a SiteBuildSettings resource.
type SiteBuildSettingsArgs struct {
	BaseDirectory           pulumi.StringPtrInput
	BranchDeployAllBranches pulumi.BoolPtrInput
	BranchDeployBranches    pulumi.StringArrayInput
	BuildCommand            pulumi.StringInput
	BuildImage              pulumi.StringPtrInput
	DeployPreviews          pulumi.BoolPtrInput
	FunctionsDirectory      pulumi.StringPtrInput
	FunctionsRegion         pulumi.StringPtrInput
	PackageDirectory        pulumi.StringPtrInput
	PrettyUrls              pulumi.BoolPtrInput
	// When enabled, prevents production deploys from sources other than the linked git repository.
	PreventNonGitProdDeploys pulumi.BoolPtrInput
	ProductionBranch         pulumi.StringInput
	PublishDirectory         pulumi.StringInput
	SiteId                   pulumi.StringInput
	StopBuilds               pulumi.BoolPtrInput
	// See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy " pulumi-lang-hcl=" netlify_waf_policy "> netlify.WafPolicy </span>resource.
	WafPolicyId pulumi.StringPtrInput
}

func (SiteBuildSettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*siteBuildSettingsArgs)(nil)).Elem()
}

type SiteBuildSettingsInput interface {
	pulumi.Input

	ToSiteBuildSettingsOutput() SiteBuildSettingsOutput
	ToSiteBuildSettingsOutputWithContext(ctx context.Context) SiteBuildSettingsOutput
}

func (*SiteBuildSettings) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteBuildSettings)(nil)).Elem()
}

func (i *SiteBuildSettings) ToSiteBuildSettingsOutput() SiteBuildSettingsOutput {
	return i.ToSiteBuildSettingsOutputWithContext(context.Background())
}

func (i *SiteBuildSettings) ToSiteBuildSettingsOutputWithContext(ctx context.Context) SiteBuildSettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SiteBuildSettingsOutput)
}

type SiteBuildSettingsOutput struct{ *pulumi.OutputState }

func (SiteBuildSettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteBuildSettings)(nil)).Elem()
}

func (o SiteBuildSettingsOutput) ToSiteBuildSettingsOutput() SiteBuildSettingsOutput {
	return o
}

func (o SiteBuildSettingsOutput) ToSiteBuildSettingsOutputWithContext(ctx context.Context) SiteBuildSettingsOutput {
	return o
}

func (o SiteBuildSettingsOutput) BaseDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.BaseDirectory }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) BranchDeployAllBranches() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.BoolOutput { return v.BranchDeployAllBranches }).(pulumi.BoolOutput)
}

func (o SiteBuildSettingsOutput) BranchDeployBranches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringArrayOutput { return v.BranchDeployBranches }).(pulumi.StringArrayOutput)
}

func (o SiteBuildSettingsOutput) BuildCommand() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.BuildCommand }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) BuildImage() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.BuildImage }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) DeployPreviews() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.BoolOutput { return v.DeployPreviews }).(pulumi.BoolOutput)
}

func (o SiteBuildSettingsOutput) FunctionsDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.FunctionsDirectory }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) FunctionsRegion() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.FunctionsRegion }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) PackageDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.PackageDirectory }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) PrettyUrls() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.BoolOutput { return v.PrettyUrls }).(pulumi.BoolOutput)
}

// When enabled, prevents production deploys from sources other than the linked git repository.
func (o SiteBuildSettingsOutput) PreventNonGitProdDeploys() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.BoolOutput { return v.PreventNonGitProdDeploys }).(pulumi.BoolOutput)
}

func (o SiteBuildSettingsOutput) ProductionBranch() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.ProductionBranch }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) PublishDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.PublishDirectory }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func (o SiteBuildSettingsOutput) StopBuilds() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.BoolOutput { return v.StopBuilds }).(pulumi.BoolOutput)
}

// See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy " pulumi-lang-hcl=" netlify_waf_policy "> netlify.WafPolicy </span>resource.
func (o SiteBuildSettingsOutput) WafPolicyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SiteBuildSettings) pulumi.StringPtrOutput { return v.WafPolicyId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SiteBuildSettingsInput)(nil)).Elem(), &SiteBuildSettings{})
	pulumi.RegisterOutputType(SiteBuildSettingsOutput{})
}
