// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SiteMetricsSettings struct {
	pulumi.CustomResourceState

	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	// Enable real user metrics. Warning: This might incur a cost on certain plans.
	RealUserMetrics pulumi.BoolPtrOutput `pulumi:"realUserMetrics"`
	// Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before disabling after enabling.
	SiteAnalytics pulumi.BoolPtrOutput `pulumi:"siteAnalytics"`
	SiteId        pulumi.StringOutput  `pulumi:"siteId"`
}

// NewSiteMetricsSettings registers a new resource with the given unique name, arguments, and options.
func NewSiteMetricsSettings(ctx *pulumi.Context,
	name string, args *SiteMetricsSettingsArgs, opts ...pulumi.ResourceOption) (*SiteMetricsSettings, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SiteMetricsSettings
	err = ctx.RegisterPackageResource("netlify:index/siteMetricsSettings:SiteMetricsSettings", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSiteMetricsSettings gets an existing SiteMetricsSettings resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSiteMetricsSettings(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SiteMetricsSettingsState, opts ...pulumi.ResourceOption) (*SiteMetricsSettings, error) {
	var resource SiteMetricsSettings
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/siteMetricsSettings:SiteMetricsSettings", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SiteMetricsSettings resources.
type siteMetricsSettingsState struct {
	LastUpdated *string `pulumi:"lastUpdated"`
	// Enable real user metrics. Warning: This might incur a cost on certain plans.
	RealUserMetrics *bool `pulumi:"realUserMetrics"`
	// Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before disabling after enabling.
	SiteAnalytics *bool   `pulumi:"siteAnalytics"`
	SiteId        *string `pulumi:"siteId"`
}

type SiteMetricsSettingsState struct {
	LastUpdated pulumi.StringPtrInput
	// Enable real user metrics. Warning: This might incur a cost on certain plans.
	RealUserMetrics pulumi.BoolPtrInput
	// Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before disabling after enabling.
	SiteAnalytics pulumi.BoolPtrInput
	SiteId        pulumi.StringPtrInput
}

func (SiteMetricsSettingsState) ElementType() reflect.Type {
	return reflect.TypeOf((*siteMetricsSettingsState)(nil)).Elem()
}

type siteMetricsSettingsArgs struct {
	// Enable real user metrics. Warning: This might incur a cost on certain plans.
	RealUserMetrics *bool `pulumi:"realUserMetrics"`
	// Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before disabling after enabling.
	SiteAnalytics *bool  `pulumi:"siteAnalytics"`
	SiteId        string `pulumi:"siteId"`
}

// The set of arguments for constructing a SiteMetricsSettings resource.
type SiteMetricsSettingsArgs struct {
	// Enable real user metrics. Warning: This might incur a cost on certain plans.
	RealUserMetrics pulumi.BoolPtrInput
	// Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before disabling after enabling.
	SiteAnalytics pulumi.BoolPtrInput
	SiteId        pulumi.StringInput
}

func (SiteMetricsSettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*siteMetricsSettingsArgs)(nil)).Elem()
}

type SiteMetricsSettingsInput interface {
	pulumi.Input

	ToSiteMetricsSettingsOutput() SiteMetricsSettingsOutput
	ToSiteMetricsSettingsOutputWithContext(ctx context.Context) SiteMetricsSettingsOutput
}

func (*SiteMetricsSettings) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteMetricsSettings)(nil)).Elem()
}

func (i *SiteMetricsSettings) ToSiteMetricsSettingsOutput() SiteMetricsSettingsOutput {
	return i.ToSiteMetricsSettingsOutputWithContext(context.Background())
}

func (i *SiteMetricsSettings) ToSiteMetricsSettingsOutputWithContext(ctx context.Context) SiteMetricsSettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SiteMetricsSettingsOutput)
}

type SiteMetricsSettingsOutput struct{ *pulumi.OutputState }

func (SiteMetricsSettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteMetricsSettings)(nil)).Elem()
}

func (o SiteMetricsSettingsOutput) ToSiteMetricsSettingsOutput() SiteMetricsSettingsOutput {
	return o
}

func (o SiteMetricsSettingsOutput) ToSiteMetricsSettingsOutputWithContext(ctx context.Context) SiteMetricsSettingsOutput {
	return o
}

func (o SiteMetricsSettingsOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteMetricsSettings) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// Enable real user metrics. Warning: This might incur a cost on certain plans.
func (o SiteMetricsSettingsOutput) RealUserMetrics() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SiteMetricsSettings) pulumi.BoolPtrOutput { return v.RealUserMetrics }).(pulumi.BoolPtrOutput)
}

// Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before disabling after enabling.
func (o SiteMetricsSettingsOutput) SiteAnalytics() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SiteMetricsSettings) pulumi.BoolPtrOutput { return v.SiteAnalytics }).(pulumi.BoolPtrOutput)
}

func (o SiteMetricsSettingsOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteMetricsSettings) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SiteMetricsSettingsInput)(nil)).Elem(), &SiteMetricsSettings{})
	pulumi.RegisterOutputType(SiteMetricsSettingsOutput{})
}
