// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SiteDomainSettings struct {
	pulumi.CustomResourceState

	BranchDeployCustomDomain  pulumi.StringPtrOutput   `pulumi:"branchDeployCustomDomain"`
	CustomDomain              pulumi.StringPtrOutput   `pulumi:"customDomain"`
	DeployPreviewCustomDomain pulumi.StringPtrOutput   `pulumi:"deployPreviewCustomDomain"`
	DomainAliases             pulumi.StringArrayOutput `pulumi:"domainAliases"`
	LastUpdated               pulumi.StringOutput      `pulumi:"lastUpdated"`
	SiteId                    pulumi.StringOutput      `pulumi:"siteId"`
}

// NewSiteDomainSettings registers a new resource with the given unique name, arguments, and options.
func NewSiteDomainSettings(ctx *pulumi.Context,
	name string, args *SiteDomainSettingsArgs, opts ...pulumi.ResourceOption) (*SiteDomainSettings, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SiteDomainSettings
	err = ctx.RegisterPackageResource("netlify:index/siteDomainSettings:SiteDomainSettings", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSiteDomainSettings gets an existing SiteDomainSettings resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSiteDomainSettings(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SiteDomainSettingsState, opts ...pulumi.ResourceOption) (*SiteDomainSettings, error) {
	var resource SiteDomainSettings
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/siteDomainSettings:SiteDomainSettings", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SiteDomainSettings resources.
type siteDomainSettingsState struct {
	BranchDeployCustomDomain  *string  `pulumi:"branchDeployCustomDomain"`
	CustomDomain              *string  `pulumi:"customDomain"`
	DeployPreviewCustomDomain *string  `pulumi:"deployPreviewCustomDomain"`
	DomainAliases             []string `pulumi:"domainAliases"`
	LastUpdated               *string  `pulumi:"lastUpdated"`
	SiteId                    *string  `pulumi:"siteId"`
}

type SiteDomainSettingsState struct {
	BranchDeployCustomDomain  pulumi.StringPtrInput
	CustomDomain              pulumi.StringPtrInput
	DeployPreviewCustomDomain pulumi.StringPtrInput
	DomainAliases             pulumi.StringArrayInput
	LastUpdated               pulumi.StringPtrInput
	SiteId                    pulumi.StringPtrInput
}

func (SiteDomainSettingsState) ElementType() reflect.Type {
	return reflect.TypeOf((*siteDomainSettingsState)(nil)).Elem()
}

type siteDomainSettingsArgs struct {
	BranchDeployCustomDomain  *string  `pulumi:"branchDeployCustomDomain"`
	CustomDomain              *string  `pulumi:"customDomain"`
	DeployPreviewCustomDomain *string  `pulumi:"deployPreviewCustomDomain"`
	DomainAliases             []string `pulumi:"domainAliases"`
	SiteId                    string   `pulumi:"siteId"`
}

// The set of arguments for constructing a SiteDomainSettings resource.
type SiteDomainSettingsArgs struct {
	BranchDeployCustomDomain  pulumi.StringPtrInput
	CustomDomain              pulumi.StringPtrInput
	DeployPreviewCustomDomain pulumi.StringPtrInput
	DomainAliases             pulumi.StringArrayInput
	SiteId                    pulumi.StringInput
}

func (SiteDomainSettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*siteDomainSettingsArgs)(nil)).Elem()
}

type SiteDomainSettingsInput interface {
	pulumi.Input

	ToSiteDomainSettingsOutput() SiteDomainSettingsOutput
	ToSiteDomainSettingsOutputWithContext(ctx context.Context) SiteDomainSettingsOutput
}

func (*SiteDomainSettings) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteDomainSettings)(nil)).Elem()
}

func (i *SiteDomainSettings) ToSiteDomainSettingsOutput() SiteDomainSettingsOutput {
	return i.ToSiteDomainSettingsOutputWithContext(context.Background())
}

func (i *SiteDomainSettings) ToSiteDomainSettingsOutputWithContext(ctx context.Context) SiteDomainSettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SiteDomainSettingsOutput)
}

type SiteDomainSettingsOutput struct{ *pulumi.OutputState }

func (SiteDomainSettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteDomainSettings)(nil)).Elem()
}

func (o SiteDomainSettingsOutput) ToSiteDomainSettingsOutput() SiteDomainSettingsOutput {
	return o
}

func (o SiteDomainSettingsOutput) ToSiteDomainSettingsOutputWithContext(ctx context.Context) SiteDomainSettingsOutput {
	return o
}

func (o SiteDomainSettingsOutput) BranchDeployCustomDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SiteDomainSettings) pulumi.StringPtrOutput { return v.BranchDeployCustomDomain }).(pulumi.StringPtrOutput)
}

func (o SiteDomainSettingsOutput) CustomDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SiteDomainSettings) pulumi.StringPtrOutput { return v.CustomDomain }).(pulumi.StringPtrOutput)
}

func (o SiteDomainSettingsOutput) DeployPreviewCustomDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SiteDomainSettings) pulumi.StringPtrOutput { return v.DeployPreviewCustomDomain }).(pulumi.StringPtrOutput)
}

func (o SiteDomainSettingsOutput) DomainAliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SiteDomainSettings) pulumi.StringArrayOutput { return v.DomainAliases }).(pulumi.StringArrayOutput)
}

func (o SiteDomainSettingsOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteDomainSettings) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o SiteDomainSettingsOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteDomainSettings) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SiteDomainSettingsInput)(nil)).Elem(), &SiteDomainSettings{})
	pulumi.RegisterOutputType(SiteDomainSettingsOutput{})
}
