// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SiteCollaborationSettings struct {
	pulumi.CustomResourceState

	LastUpdated                   pulumi.StringOutput `pulumi:"lastUpdated"`
	NetlifyDrawerInBranchDeploys  pulumi.BoolOutput   `pulumi:"netlifyDrawerInBranchDeploys"`
	NetlifyDrawerInDeployPreviews pulumi.BoolOutput   `pulumi:"netlifyDrawerInDeployPreviews"`
	NetlifyHeadsUpDisplay         pulumi.BoolOutput   `pulumi:"netlifyHeadsUpDisplay"`
	SiteId                        pulumi.StringOutput `pulumi:"siteId"`
}

// NewSiteCollaborationSettings registers a new resource with the given unique name, arguments, and options.
func NewSiteCollaborationSettings(ctx *pulumi.Context,
	name string, args *SiteCollaborationSettingsArgs, opts ...pulumi.ResourceOption) (*SiteCollaborationSettings, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NetlifyDrawerInBranchDeploys == nil {
		return nil, errors.New("invalid value for required argument 'NetlifyDrawerInBranchDeploys'")
	}
	if args.NetlifyDrawerInDeployPreviews == nil {
		return nil, errors.New("invalid value for required argument 'NetlifyDrawerInDeployPreviews'")
	}
	if args.NetlifyHeadsUpDisplay == nil {
		return nil, errors.New("invalid value for required argument 'NetlifyHeadsUpDisplay'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SiteCollaborationSettings
	err = ctx.RegisterPackageResource("netlify:index/siteCollaborationSettings:SiteCollaborationSettings", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSiteCollaborationSettings gets an existing SiteCollaborationSettings resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSiteCollaborationSettings(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SiteCollaborationSettingsState, opts ...pulumi.ResourceOption) (*SiteCollaborationSettings, error) {
	var resource SiteCollaborationSettings
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/siteCollaborationSettings:SiteCollaborationSettings", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SiteCollaborationSettings resources.
type siteCollaborationSettingsState struct {
	LastUpdated                   *string `pulumi:"lastUpdated"`
	NetlifyDrawerInBranchDeploys  *bool   `pulumi:"netlifyDrawerInBranchDeploys"`
	NetlifyDrawerInDeployPreviews *bool   `pulumi:"netlifyDrawerInDeployPreviews"`
	NetlifyHeadsUpDisplay         *bool   `pulumi:"netlifyHeadsUpDisplay"`
	SiteId                        *string `pulumi:"siteId"`
}

type SiteCollaborationSettingsState struct {
	LastUpdated                   pulumi.StringPtrInput
	NetlifyDrawerInBranchDeploys  pulumi.BoolPtrInput
	NetlifyDrawerInDeployPreviews pulumi.BoolPtrInput
	NetlifyHeadsUpDisplay         pulumi.BoolPtrInput
	SiteId                        pulumi.StringPtrInput
}

func (SiteCollaborationSettingsState) ElementType() reflect.Type {
	return reflect.TypeOf((*siteCollaborationSettingsState)(nil)).Elem()
}

type siteCollaborationSettingsArgs struct {
	NetlifyDrawerInBranchDeploys  bool   `pulumi:"netlifyDrawerInBranchDeploys"`
	NetlifyDrawerInDeployPreviews bool   `pulumi:"netlifyDrawerInDeployPreviews"`
	NetlifyHeadsUpDisplay         bool   `pulumi:"netlifyHeadsUpDisplay"`
	SiteId                        string `pulumi:"siteId"`
}

// The set of arguments for constructing a SiteCollaborationSettings resource.
type SiteCollaborationSettingsArgs struct {
	NetlifyDrawerInBranchDeploys  pulumi.BoolInput
	NetlifyDrawerInDeployPreviews pulumi.BoolInput
	NetlifyHeadsUpDisplay         pulumi.BoolInput
	SiteId                        pulumi.StringInput
}

func (SiteCollaborationSettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*siteCollaborationSettingsArgs)(nil)).Elem()
}

type SiteCollaborationSettingsInput interface {
	pulumi.Input

	ToSiteCollaborationSettingsOutput() SiteCollaborationSettingsOutput
	ToSiteCollaborationSettingsOutputWithContext(ctx context.Context) SiteCollaborationSettingsOutput
}

func (*SiteCollaborationSettings) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteCollaborationSettings)(nil)).Elem()
}

func (i *SiteCollaborationSettings) ToSiteCollaborationSettingsOutput() SiteCollaborationSettingsOutput {
	return i.ToSiteCollaborationSettingsOutputWithContext(context.Background())
}

func (i *SiteCollaborationSettings) ToSiteCollaborationSettingsOutputWithContext(ctx context.Context) SiteCollaborationSettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SiteCollaborationSettingsOutput)
}

type SiteCollaborationSettingsOutput struct{ *pulumi.OutputState }

func (SiteCollaborationSettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SiteCollaborationSettings)(nil)).Elem()
}

func (o SiteCollaborationSettingsOutput) ToSiteCollaborationSettingsOutput() SiteCollaborationSettingsOutput {
	return o
}

func (o SiteCollaborationSettingsOutput) ToSiteCollaborationSettingsOutputWithContext(ctx context.Context) SiteCollaborationSettingsOutput {
	return o
}

func (o SiteCollaborationSettingsOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteCollaborationSettings) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o SiteCollaborationSettingsOutput) NetlifyDrawerInBranchDeploys() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteCollaborationSettings) pulumi.BoolOutput { return v.NetlifyDrawerInBranchDeploys }).(pulumi.BoolOutput)
}

func (o SiteCollaborationSettingsOutput) NetlifyDrawerInDeployPreviews() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteCollaborationSettings) pulumi.BoolOutput { return v.NetlifyDrawerInDeployPreviews }).(pulumi.BoolOutput)
}

func (o SiteCollaborationSettingsOutput) NetlifyHeadsUpDisplay() pulumi.BoolOutput {
	return o.ApplyT(func(v *SiteCollaborationSettings) pulumi.BoolOutput { return v.NetlifyHeadsUpDisplay }).(pulumi.BoolOutput)
}

func (o SiteCollaborationSettingsOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *SiteCollaborationSettings) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SiteCollaborationSettingsInput)(nil)).Elem(), &SiteCollaborationSettings{})
	pulumi.RegisterOutputType(SiteCollaborationSettingsOutput{})
}
