// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TeamFirewallTrafficRules struct {
	pulumi.CustomResourceState

	LastUpdated pulumi.StringOutput                     `pulumi:"lastUpdated"`
	Published   TeamFirewallTrafficRulesPublishedOutput `pulumi:"published"`
	SiteId      pulumi.StringOutput                     `pulumi:"siteId"`
	// Required if a default team was not configured in the provider configuration.
	TeamId      pulumi.StringOutput                       `pulumi:"teamId"`
	Unpublished TeamFirewallTrafficRulesUnpublishedOutput `pulumi:"unpublished"`
}

// NewTeamFirewallTrafficRules registers a new resource with the given unique name, arguments, and options.
func NewTeamFirewallTrafficRules(ctx *pulumi.Context,
	name string, args *TeamFirewallTrafficRulesArgs, opts ...pulumi.ResourceOption) (*TeamFirewallTrafficRules, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Published == nil {
		return nil, errors.New("invalid value for required argument 'Published'")
	}
	if args.Unpublished == nil {
		return nil, errors.New("invalid value for required argument 'Unpublished'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource TeamFirewallTrafficRules
	err = ctx.RegisterPackageResource("netlify:index/teamFirewallTrafficRules:TeamFirewallTrafficRules", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTeamFirewallTrafficRules gets an existing TeamFirewallTrafficRules resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTeamFirewallTrafficRules(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TeamFirewallTrafficRulesState, opts ...pulumi.ResourceOption) (*TeamFirewallTrafficRules, error) {
	var resource TeamFirewallTrafficRules
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/teamFirewallTrafficRules:TeamFirewallTrafficRules", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TeamFirewallTrafficRules resources.
type teamFirewallTrafficRulesState struct {
	LastUpdated *string                            `pulumi:"lastUpdated"`
	Published   *TeamFirewallTrafficRulesPublished `pulumi:"published"`
	SiteId      *string                            `pulumi:"siteId"`
	// Required if a default team was not configured in the provider configuration.
	TeamId      *string                              `pulumi:"teamId"`
	Unpublished *TeamFirewallTrafficRulesUnpublished `pulumi:"unpublished"`
}

type TeamFirewallTrafficRulesState struct {
	LastUpdated pulumi.StringPtrInput
	Published   TeamFirewallTrafficRulesPublishedPtrInput
	SiteId      pulumi.StringPtrInput
	// Required if a default team was not configured in the provider configuration.
	TeamId      pulumi.StringPtrInput
	Unpublished TeamFirewallTrafficRulesUnpublishedPtrInput
}

func (TeamFirewallTrafficRulesState) ElementType() reflect.Type {
	return reflect.TypeOf((*teamFirewallTrafficRulesState)(nil)).Elem()
}

type teamFirewallTrafficRulesArgs struct {
	Published TeamFirewallTrafficRulesPublished `pulumi:"published"`
	// Required if a default team was not configured in the provider configuration.
	TeamId      *string                             `pulumi:"teamId"`
	Unpublished TeamFirewallTrafficRulesUnpublished `pulumi:"unpublished"`
}

// The set of arguments for constructing a TeamFirewallTrafficRules resource.
type TeamFirewallTrafficRulesArgs struct {
	Published TeamFirewallTrafficRulesPublishedInput
	// Required if a default team was not configured in the provider configuration.
	TeamId      pulumi.StringPtrInput
	Unpublished TeamFirewallTrafficRulesUnpublishedInput
}

func (TeamFirewallTrafficRulesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*teamFirewallTrafficRulesArgs)(nil)).Elem()
}

type TeamFirewallTrafficRulesInput interface {
	pulumi.Input

	ToTeamFirewallTrafficRulesOutput() TeamFirewallTrafficRulesOutput
	ToTeamFirewallTrafficRulesOutputWithContext(ctx context.Context) TeamFirewallTrafficRulesOutput
}

func (*TeamFirewallTrafficRules) ElementType() reflect.Type {
	return reflect.TypeOf((**TeamFirewallTrafficRules)(nil)).Elem()
}

func (i *TeamFirewallTrafficRules) ToTeamFirewallTrafficRulesOutput() TeamFirewallTrafficRulesOutput {
	return i.ToTeamFirewallTrafficRulesOutputWithContext(context.Background())
}

func (i *TeamFirewallTrafficRules) ToTeamFirewallTrafficRulesOutputWithContext(ctx context.Context) TeamFirewallTrafficRulesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TeamFirewallTrafficRulesOutput)
}

type TeamFirewallTrafficRulesOutput struct{ *pulumi.OutputState }

func (TeamFirewallTrafficRulesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TeamFirewallTrafficRules)(nil)).Elem()
}

func (o TeamFirewallTrafficRulesOutput) ToTeamFirewallTrafficRulesOutput() TeamFirewallTrafficRulesOutput {
	return o
}

func (o TeamFirewallTrafficRulesOutput) ToTeamFirewallTrafficRulesOutputWithContext(ctx context.Context) TeamFirewallTrafficRulesOutput {
	return o
}

func (o TeamFirewallTrafficRulesOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *TeamFirewallTrafficRules) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o TeamFirewallTrafficRulesOutput) Published() TeamFirewallTrafficRulesPublishedOutput {
	return o.ApplyT(func(v *TeamFirewallTrafficRules) TeamFirewallTrafficRulesPublishedOutput { return v.Published }).(TeamFirewallTrafficRulesPublishedOutput)
}

func (o TeamFirewallTrafficRulesOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *TeamFirewallTrafficRules) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// Required if a default team was not configured in the provider configuration.
func (o TeamFirewallTrafficRulesOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *TeamFirewallTrafficRules) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

func (o TeamFirewallTrafficRulesOutput) Unpublished() TeamFirewallTrafficRulesUnpublishedOutput {
	return o.ApplyT(func(v *TeamFirewallTrafficRules) TeamFirewallTrafficRulesUnpublishedOutput { return v.Unpublished }).(TeamFirewallTrafficRulesUnpublishedOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TeamFirewallTrafficRulesInput)(nil)).Elem(), &TeamFirewallTrafficRules{})
	pulumi.RegisterOutputType(TeamFirewallTrafficRulesOutput{})
}
