// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netlify

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/netlify/netlify/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WafPolicy struct {
	pulumi.CustomResourceState

	Description pulumi.StringOutput         `pulumi:"description"`
	LastUpdated pulumi.StringOutput         `pulumi:"lastUpdated"`
	Name        pulumi.StringOutput         `pulumi:"name"`
	RuleSets    WafPolicyRuleSetArrayOutput `pulumi:"ruleSets"`
	TeamId      pulumi.StringOutput         `pulumi:"teamId"`
}

// NewWafPolicy registers a new resource with the given unique name, arguments, and options.
func NewWafPolicy(ctx *pulumi.Context,
	name string, args *WafPolicyArgs, opts ...pulumi.ResourceOption) (*WafPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.RuleSets == nil {
		return nil, errors.New("invalid value for required argument 'RuleSets'")
	}
	if args.TeamId == nil {
		return nil, errors.New("invalid value for required argument 'TeamId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource WafPolicy
	err = ctx.RegisterPackageResource("netlify:index/wafPolicy:WafPolicy", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWafPolicy gets an existing WafPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWafPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WafPolicyState, opts ...pulumi.ResourceOption) (*WafPolicy, error) {
	var resource WafPolicy
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("netlify:index/wafPolicy:WafPolicy", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WafPolicy resources.
type wafPolicyState struct {
	Description *string            `pulumi:"description"`
	LastUpdated *string            `pulumi:"lastUpdated"`
	Name        *string            `pulumi:"name"`
	RuleSets    []WafPolicyRuleSet `pulumi:"ruleSets"`
	TeamId      *string            `pulumi:"teamId"`
}

type WafPolicyState struct {
	Description pulumi.StringPtrInput
	LastUpdated pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	RuleSets    WafPolicyRuleSetArrayInput
	TeamId      pulumi.StringPtrInput
}

func (WafPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*wafPolicyState)(nil)).Elem()
}

type wafPolicyArgs struct {
	Description string             `pulumi:"description"`
	Name        *string            `pulumi:"name"`
	RuleSets    []WafPolicyRuleSet `pulumi:"ruleSets"`
	TeamId      string             `pulumi:"teamId"`
}

// The set of arguments for constructing a WafPolicy resource.
type WafPolicyArgs struct {
	Description pulumi.StringInput
	Name        pulumi.StringPtrInput
	RuleSets    WafPolicyRuleSetArrayInput
	TeamId      pulumi.StringInput
}

func (WafPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*wafPolicyArgs)(nil)).Elem()
}

type WafPolicyInput interface {
	pulumi.Input

	ToWafPolicyOutput() WafPolicyOutput
	ToWafPolicyOutputWithContext(ctx context.Context) WafPolicyOutput
}

func (*WafPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**WafPolicy)(nil)).Elem()
}

func (i *WafPolicy) ToWafPolicyOutput() WafPolicyOutput {
	return i.ToWafPolicyOutputWithContext(context.Background())
}

func (i *WafPolicy) ToWafPolicyOutputWithContext(ctx context.Context) WafPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WafPolicyOutput)
}

type WafPolicyOutput struct{ *pulumi.OutputState }

func (WafPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WafPolicy)(nil)).Elem()
}

func (o WafPolicyOutput) ToWafPolicyOutput() WafPolicyOutput {
	return o
}

func (o WafPolicyOutput) ToWafPolicyOutputWithContext(ctx context.Context) WafPolicyOutput {
	return o
}

func (o WafPolicyOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *WafPolicy) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o WafPolicyOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *WafPolicy) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

func (o WafPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WafPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o WafPolicyOutput) RuleSets() WafPolicyRuleSetArrayOutput {
	return o.ApplyT(func(v *WafPolicy) WafPolicyRuleSetArrayOutput { return v.RuleSets }).(WafPolicyRuleSetArrayOutput)
}

func (o WafPolicyOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *WafPolicy) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WafPolicyInput)(nil)).Elem(), &WafPolicy{})
	pulumi.RegisterOutputType(WafPolicyOutput{})
}
